### ISSUE TITLE
Refactor `weather_summary`

### ISSUE THREAD

**Issue by ian-flores** [merely-useful/kenyaweather#1]
`weather_summary` uses a very manual process between lines 23 to 44. I would like for us to refactor this to be more in accordance with the tidyverse; even if it's not as explicit code.

**Comment by cwickham** [comment]
Yeah, agreed.  The second two chunks can be replaced by:
```{r}
  yearly_stats %>%
    dplyr::summarise(dplyr::across(prcp:tmin, list(mean = mean, sd = sd)))
```
Let me think on the first two...

**Comment by cwickham** [comment]
With a little reshaping this would work:
```{r}
yearly_stats %>% 
    dplyr::summarise(dplyr::across(prcp:tmin, 
      list(
        mean = mean, 
        sd = sd,
        max_year =  ~ dplyr::cur_data()$year[.x == max(.x)],
        min_year = ~ dplyr::cur_data()$year[.x == min(.x)]
      )
    )
  )
```

But given how long it took me, it might be too complex an approach.  I suspect there is an easier way...I'll keep thinking on it.

It occurred to me, that along with which year the min and max occurred, I wanted to know what those extremes were.  I wonder if splitting out the extremes part into a separate function `weather_extremes()` might also simplify the body of this function.
